language: ruby
sudo: false
rvm: 2.2.0
script: bundle exec rake deploy
env:
  global:
    secure: LwyuMdvHPT7vRq0Sqn9SYoHECykv/ztkRDZDKASwdI01BMklAy4KYWa3PqNuWB3FBZ5ezm+39X2bFLYwBbDFyux/nTRgbJKxcP6FOe+sXvE7pcGf2mwlpn5AnLf5dHF/4Lwf6BiYtr96r7SXRT/d21Z4OlfKpvfmU94s/kNsbBDMdAiIxaGa7Kbr6CDnLIwEgmAAXmIxkOcWSmvUdYVXAvmguVGG+hV8dlaTlFW5fvq0kbOlSce+GaWfYRpFYg7dyySjxPvXDxjYwaD42cvztN77nI/gTUPR5+UxKkxbBnXXZDLPgwbngj671ZTkzv5fNgxiyUOozAS0kzJWv7yfmuV4rhMKxTVT30ETpMXu+z7kVSt8iiNpK7bCY2o6mFDzC2woTG45BNKbR0TW8uIghhm47BsBbP5ALz2gTf1nEA3fTehrqZpaBl5styTX91k11EJjyGSQmipwyydHWjKauNQ0yVUiLbaGf//rJiJVPo6iIbGwnxU1/4MwVa4xBplP7M4k5K9zZvOCm2fek6edlinuOWBmpXeMKDoXlWdgGEg8rqqvDUtH59Pnfri5n0YW/FFqlBgmp4bjmF7gzr/meyMvwJGWIZNpOu7LcXq3aCAuzT2lM8H2zEFiGWDfBtJaXZFQ+1edDssnjsh6Fczq6kMjH+8lx+n4fL0ewCQ2kIQ=
exclude: [vendor]
